List<String> berufe = [
  'Bäcker',
  'Arzt',
  'Ingenieur',
  'Anwalt',
  'Lehrer',
  'Kellner',
  'Friseur',
  'Architekt',
  'Manager',
  'Designer',
  'Pilot',
  'Journalist',
  'Verkäufer',
  'Mechaniker',
  'Polizist',
  'Feuerwehrmann',
  'Tierarzt',
  'Maler',
  'Elektriker',
  'Fotograf',
  'Schreiner',
  'Installateur',
  'Klempner',
  'Tischler',
  'Landwirt',
  'Metzger',
  'Florist',
  'Gärtner',
  'Maurer',
  'LKW-Fahrer',
  'Politiker',
  'Schauspieler',
  'Programmierer',
  'Banker',
  'Forscher',
  'Zahnarzt',
  'Psychologe',
  'Athlet',
  'Militär',
  'Chemiker'
];

List<String> obst = [
  'Apfel',
  'Banane',
  'Orange',
  'Birne',
  'Traube',
  'Kiwi',
  'Erdbeere',
  'Himbeere',
  'Heidelbeere',
  'Melone',
  'Wassermelone',
  'Pfirsich',
  'Nektarine',
  'Ananas',
  'Mango',
  'Granatapfel',
  'Limette',
  'Zitrone',
  'Mandarine',
  'Papaya',
  'Physalis',
  'Passionsfrucht',
  'Guave',
  'Quitte',
  'Kaki',
  'Feige',
  'Grapefruit',
  'Kumquat',
  'Cherimoya',
  'Kirsche',
  'Aprikose',
  'Clementine',
  'Mirabelle',
  'Pflaume',
  'Holunder',
  'Johannisbeere',
  'Stachelbeere',
  'Brombeere',
  'Schwarze Johannisbeere',
  'Cranberry'
];

List<String> essen = [
  'Pizza',
  'Hamburger',
  'Pommes frites',
  'Spaghetti',
  'Lasagne',
  'Sushi',
  'Steak',
  'Burrito',
  'Sandwich',
  'Salat',
  'Kebab',
  'Fajitas',
  'Taco',
  'Falafel',
  'Chicken Wings',
  'Bratkartoffeln',
  'Nudelsuppe',
  'Risotto',
  'Ramen-Nudeln',
  'Dumplings',
  'Gyros',
  'Moussaka',
  'Pastete',
  'Curry',
  'Enchiladas',
  'Wok-Gemüse',
  'Quesadillas',
  'Reis mit Hühnchen',
  'Linsensuppe',
  'Grillgemüse',
  'Gulaschsuppe',
  'Kartoffelbrei',
  'Rindfleisch-Eintopf',
  'Fish and Chips',
  'Meeresfrüchte',
  'Tortilla-Chips',
  'Knoblauchbrot',
  'Schaschlik',
  'Paella'
];

List<String> staedte = [
  'Berlin',
  'London',
  'Paris',
  'New York City',
  'Rom',
  'Istanbul',
  'Madrid',
  'Barcelona',
  'Moskau',
  'Dubai',
  'Singapur',
  'Hongkong',
  'San Francisco',
  'Los Angeles',
  'Tokio',
  'Shanghai',
  'Seoul',
  'Sydney',
  'Bangkok',
  'Osaka',
  'Delhi',
  'Jakarta',
  'Manila',
  'Kairo',
  'Kuala Lumpur',
  'Mexiko-Stadt',
  'Rio de Janeiro',
  'Buenos Aires',
  'Hanoi',
  'Ho Chi Minh Stadt',
  'Toronto',
  'Vancouver',
  'Neuseeland',
  'Edinburgh',
  'Stockholm',
  'Amsterdam',
  'Brüssel',
  'Wien',
  'Zürich',
  'München',
  'Hamburg'
];
